# Generated by Django 5.2 on 2025-05-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_org_id", models.CharField(max_length=50)),
                ("account_id", models.CharField(max_length=50)),
                ("touchpoint_id", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField()),
                ("activity", models.TextField()),
                ("channel", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("record_type", models.CharField(max_length=100)),
                ("source_record_type", models.CharField(max_length=100)),
                ("source_record_id", models.CharField(max_length=255)),
                (
                    "campaign_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("direction", models.CharField(max_length=10)),
                ("people", models.JSONField()),
                ("involved_team_ids", models.JSONField()),
                ("related_opportunity_ids", models.JSONField()),
                ("activity_grouping_id", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
