# Generated by Django 5.2 on 2025-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_activityevent_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("customer_org_id", models.CharField(max_length=60)),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "unique_together": {("customer_org_id", "id")},
            },
        ),
    ]
